"""Agent 2 — BRD + RTM.

Role in the pipeline
--------------------
Takes the obligations produced by Agent 1 and produces two business
artefacts:

* :class:`~models.workflow_models.BRDArtifact` — the structured BRD/FRD
  report (already generated by Agent 1; this agent wraps it and optionally
  writes the DOCX export).
* :class:`~models.workflow_models.RTMArtifact` — a Requirements Traceability
  Matrix mapping each obligation to:

    - business requirement (BR-XXX)
    - functional requirement (FR-XXX) when one can be inferred
    - impacted area + function
    - system / process impact
    - evidence required
    - traceability ID

Implementation strategy
-----------------------
* The BRD already exists inside the :class:`RegulatoryAnalysis` produced by
  Agent 1, so we never regenerate it here.
* The RTM is built deterministically by joining obligations against the BRD's
  functional-requirement section using shared themes/areas/keywords.
* If the caller asks for the DOCX export we delegate to
  :func:`services.brd_frd_generator.write_brd_docx` — no logic duplication.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from models.workflow_models import (
    BRDArtifact,
    Obligation,
    RegulatoryAnalysis,
    RTMArtifact,
    RTMEntry,
)
from services.brd_frd_generator import (
    DoraDetailedBRD,
    RequirementItem,
    write_brd_docx,
)


class BRDRTMAgent:
    """Agent 2 implementation."""

    def build(
        self,
        analysis: RegulatoryAnalysis,
        *,
        docx_export_path: Optional[Path] = None,
        tier: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Return a dict with ``brd`` and ``rtm`` artefacts.

        Returning a dict (rather than a tuple) keeps the call-site readable
        from the orchestrator and is easy to extend with future artefacts.
        """
        brd_artifact = self._wrap_brd(analysis, docx_export_path, tier or analysis.tier)
        rtm_artifact = self._build_rtm(analysis.obligations, analysis.brd_report)
        return {"brd": brd_artifact, "rtm": rtm_artifact}

    def build_rtm_only(self, obligations: Sequence[Obligation],
                       brd_report: Optional[DoraDetailedBRD] = None) -> RTMArtifact:
        """Build only the RTM. Used by orchestration paths that already hold
        a BRD artefact (for example when re-running scoring on an existing BRD)."""
        return self._build_rtm(obligations, brd_report)

    # ------------------------------------------------------------------
    # BRD wrapping
    # ------------------------------------------------------------------

    @staticmethod
    def _wrap_brd(
        analysis: RegulatoryAnalysis,
        docx_export_path: Optional[Path],
        tier: str,
    ) -> BRDArtifact:
        report = analysis.brd_report
        if report is None:
            return BRDArtifact(report=None, metadata=analysis.metadata, source="missing")

        # Forward source traceability into the DOCX writer so the rendered
        # document carries both the per-row "Source References" column and
        # the dedicated "Source References" master section.
        metadata = dict(analysis.metadata or {})
        source_refs_by_item = metadata.get("source_references_by_item") or {}
        source_catalogue = metadata.get("source_references_catalogue") or []

        docx_path: Optional[str] = None
        if docx_export_path is not None:
            try:
                docx_path = write_brd_docx(
                    report,
                    str(docx_export_path),
                    tier=tier,
                    source_references_by_item=source_refs_by_item,
                    source_catalogue=source_catalogue,
                )
            except Exception:
                docx_path = None
        return BRDArtifact(
            report=report,
            metadata=metadata,
            docx_path=docx_path,
            source="generated",
        )

    # ------------------------------------------------------------------
    # RTM construction
    # ------------------------------------------------------------------

    @staticmethod
    def _build_rtm(
        obligations: Sequence[Obligation],
        brd_report: Optional[DoraDetailedBRD],
    ) -> RTMArtifact:
        functional_index = _index_functional_requirements(brd_report) if brd_report else {}

        entries: List[RTMEntry] = []
        for idx, obligation in enumerate(obligations, start=1):
            fr_id, fr_text = _pick_functional_requirement(obligation, functional_index)
            entries.append(RTMEntry(
                traceability_id=f"TR-{idx:04d}",
                obligation_id=obligation.obligation_id,
                business_requirement_id=obligation.source_requirement_id or obligation.obligation_id,
                functional_requirement_id=fr_id,
                business_requirement=obligation.compliance_requirement or obligation.title,
                functional_requirement=fr_text,
                impacted_area=obligation.impacted_area,
                impacted_function=obligation.impacted_function,
                system_process_impact=_system_process_impact(obligation),
                evidence_required=", ".join(obligation.evidence_needs)
                                  if obligation.evidence_needs else "Evidence to be defined",
                regulatory_basis=obligation.regulatory_basis,
                priority=obligation.priority,
                # Carry obligation's citations onto the RTM row so exported
                # JSON/CSV stays self-contained for downstream consumers.
                source_references=list(getattr(obligation, "source_references", []) or []),
            ))

        metadata = {
            "entry_count": len(entries),
            "covered_functions": sorted({e.impacted_function for e in entries}),
            "covered_areas": sorted({e.impacted_area for e in entries}),
            "top_themes": [t for t, _ in Counter(o.theme for o in obligations).most_common(5)],
        }
        return RTMArtifact(entries=entries, metadata=metadata)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _index_functional_requirements(report: DoraDetailedBRD) -> Dict[str, RequirementItem]:
    """Return ``{normalized lowercase keyword bag -> FR item}`` for matching."""
    index: Dict[str, RequirementItem] = {}
    for item in report.functional_requirements.items:
        key = " ".join([
            item.category or "",
            item.requirement or "",
            item.detailed_requirement or "",
        ]).lower()
        index[key] = item
    return index


def _pick_functional_requirement(
    obligation: Obligation,
    fr_index: Dict[str, RequirementItem],
) -> tuple[Optional[str], str]:
    """Pick the best-matching FR for an obligation using simple keyword overlap."""
    if not fr_index:
        return None, "Functional requirement to be elaborated during BRD/FRD workshop."
    tokens = {
        t for t in
        (obligation.title + " " + obligation.compliance_requirement
         + " " + obligation.theme).lower().split()
        if len(t) > 4
    }
    best: Optional[RequirementItem] = None
    best_score = 0
    for haystack, item in fr_index.items():
        score = sum(1 for token in tokens if token in haystack)
        if score > best_score:
            best_score = score
            best = item
    if best is None or best_score == 0:
        return None, "Functional requirement to be elaborated during BRD/FRD workshop."
    return best.id, best.detailed_requirement or best.requirement


def _system_process_impact(obligation: Obligation) -> str:
    area = obligation.impacted_area or "the impacted area"
    function = obligation.impacted_function or "the impacted function"
    return (
        f"Implementation impacts {function} operating within the {area} domain. "
        f"Expected impact spans process, data, and reporting controls aligned to "
        f"{obligation.regulatory_basis or 'the mapped regulation'}."
    )


__all__ = ["BRDRTMAgent"]
