"""Agent 3 — AI-Driven Questionnaire Generation.

Role in the pipeline
--------------------
Takes the :class:`BRDArtifact` (and optionally :class:`RTMArtifact` +
:class:`RegulatoryAnalysis` + :class:`ImpactAssessment`) and emits a
:class:`~models.workflow_models.QuestionnairePackage` whose questions,
options, per-option scoring, follow-up branching, and team routing are
generated by a GenAI agent — **not** by hardcoded templates.

Implementation strategy
-----------------------
* The heavy lifting lives in
  :mod:`services.ai_questionnaire_generator` (Pydantic-structured prompts
  against GPT-4o). This module simply feeds it the full working context:
  BRD requirements + source references, regulatory obligations, RTM
  control mappings, impact severity signals, and the selected client
  role(s).
* :mod:`services.questionnaire_generator` is used only as a thin adapter:
  it derives impact pairs from the BRD, calls the AI generator, and
  hydrates the response back into the on-wire ``QuestionnairePackage``
  schema so the deterministic Rules Engine keeps working.
* :func:`services.questionnaire_enhancer.enhance_questionnaire_package`
  post-processes the AI output to (re-)weight questions proportional to
  the regulatory impact severity per business area and reorder them so
  the highest-impact areas surface first.
* Supports three input modes:

    1. ``from_report``    — closed-loop path from a generated BRD model.
    2. ``from_docx``      — parses an uploaded BRD/FRD DOCX.
    3. ``from_package``   — validates and loads an externally-supplied JSON
                            package (e.g. uploaded sample).

Offline behaviour
-----------------
When no :class:`GenAIClient` is passed (or the shared client is disabled
via env), the AI generator falls back to synthesising a small number of
"manual review required" placeholder questions traceable to real
obligations / requirements — it never invents questionnaire content.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence, Union

from models.workflow_models import (
    BRDArtifact,
    ImpactAssessment,
    Obligation,
    QuestionnairePackage,
    ReadinessAssessment,
    RegulatoryAnalysis,
    RTMArtifact,
)
from services.client_roles import (
    APPLICABILITY_APPLICABLE,
    APPLICABILITY_NOT_APPLICABLE,
    APPLICABILITY_PARTIAL,
    APPLICABILITY_UNCERTAIN,
    normalize_client_roles,
)
from services.genai_service import GenAIClient
from services.questionnaire_enhancer import enhance_questionnaire_package
from services.questionnaire_generator import (
    build_package_from_report,
    build_questionnaire_package,
)
from utils.json_utils import validate_package_schema

DocxPath = Union[str, Path]


class QuestionnaireAgent:
    """Agent 3 implementation."""

    def from_report(
        self,
        brd: BRDArtifact,
        *,
        regulation: str = "DORA",
        name: Optional[str] = None,
        impact: Optional[ImpactAssessment] = None,
        readiness: Optional[ReadinessAssessment] = None,
        analysis: Optional[RegulatoryAnalysis] = None,
        rtm: Optional[RTMArtifact] = None,
        client_roles: Optional[Sequence[str]] = None,
        client_profile: Optional[Mapping[str, Any]] = None,
        client: Optional[GenAIClient] = None,
    ) -> QuestionnairePackage:
        """Build an AI-generated questionnaire from a BRD.

        The heavy lifting is done by
        :func:`services.ai_questionnaire_generator.generate_ai_questionnaire`
        (invoked through
        :func:`services.questionnaire_generator.build_package_from_report`),
        which receives:

        * the BRD requirements + source references (traceability),
        * the impact pairs derived from the BRD (area/function coverage),
        * the regulatory obligations from Agent 1 (regulatory basis + rationale),
        * the RTM entries from Agent 2 (control mapping),
        * the :class:`ImpactAssessment` (severity signal for prioritisation),
        * the selected client roles + client profile (in-scope tailoring),
        * the shared GenAI client (empty ⇒ offline manual-review fallback).

        After AI generation the package is enriched with impact weights and
        (optionally) filtered to the selected institution roles.
        """
        if brd is None or brd.report is None:
            raise ValueError(
                "BRD artefact does not contain an in-memory report. "
                "Generate the BRD first or use from_docx() / from_package()."
            )
        source_refs = (brd.metadata or {}).get("source_references_by_item") or {}
        obligations = list(getattr(analysis, "obligations", []) or [])
        rtm_entries = list(getattr(rtm, "entries", []) or []) if rtm else []
        roles = _resolve_roles(analysis, client_roles)
        package = build_package_from_report(
            brd.report,
            regulation=regulation,
            source_refs_by_item=source_refs,
            obligations=obligations,
            rtm_entries=rtm_entries,
            impact=impact,
            readiness=readiness,
            client_roles=roles,
            client_profile=client_profile,
            client=client,
        )
        try:
            enhance_questionnaire_package(
                package, impact=impact, regulation=regulation,
            )
        except Exception:
            # Enhancement is best-effort — never break the pipeline.
            pass

        if roles:
            _apply_role_filter(package, analysis=analysis, client_roles=roles,
                               regulation=regulation)

        return QuestionnairePackage(
            package=package,
            source="generated_brd",
            name=name or f"{regulation} — generated from BRD",
        )

    def from_docx(
        self,
        path: DocxPath,
        *,
        regulation: str = "DORA",
        name: Optional[str] = None,
        impact: Optional[ImpactAssessment] = None,
        readiness: Optional[ReadinessAssessment] = None,
        analysis: Optional[RegulatoryAnalysis] = None,
        rtm: Optional[RTMArtifact] = None,
        client_roles: Optional[Sequence[str]] = None,
        client_profile: Optional[Mapping[str, Any]] = None,
        client: Optional[GenAIClient] = None,
    ) -> QuestionnairePackage:
        """Parse a BRD/FRD DOCX and build an AI-generated questionnaire.

        The role-aware filter is also applied here so uploaded BRDs behave
        identically to generated ones once a client role is selected.
        """
        obligations = list(getattr(analysis, "obligations", []) or [])
        rtm_entries = list(getattr(rtm, "entries", []) or []) if rtm else []
        roles = _resolve_roles(analysis, client_roles)
        package = build_questionnaire_package(
            str(path),
            regulation=regulation,
            obligations=obligations,
            rtm_entries=rtm_entries,
            impact=impact,
            readiness=readiness,
            client_roles=roles,
            client_profile=client_profile,
            client=client,
        )
        try:
            enhance_questionnaire_package(
                package, impact=impact, regulation=regulation,
            )
        except Exception:
            pass

        if roles:
            _apply_role_filter(package, analysis=analysis, client_roles=roles,
                               regulation=regulation)

        return QuestionnairePackage(
            package=package,
            source="uploaded_brd",
            name=name or f"{regulation} — from {Path(path).stem}",
        )

    def from_package(
        self,
        package: Mapping[str, Any],
        *,
        source: str = "uploaded_json",
        name: Optional[str] = None,
        analysis: Optional[RegulatoryAnalysis] = None,
        client_roles: Optional[Sequence[str]] = None,
    ) -> QuestionnairePackage:
        """Validate then load an existing questionnaire-package dict / JSON."""
        issues = validate_package_schema(package)
        if issues:
            raise ValueError(
                "Questionnaire package failed schema validation:\n  - "
                + "\n  - ".join(issues)
            )
        pkg = dict(package)
        roles = _resolve_roles(analysis, client_roles)
        if roles:
            _apply_role_filter(
                pkg, analysis=analysis, client_roles=roles,
                regulation=str(pkg.get("metadata", {}).get("regulation") or ""),
            )
        return QuestionnairePackage(
            package=pkg,
            source=source,
            name=name,
        )


# ---------------------------------------------------------------------------
# Client Role-Aware filter helpers
# ---------------------------------------------------------------------------

def _resolve_roles(
    analysis: Optional[RegulatoryAnalysis],
    client_roles: Optional[Sequence[str]],
) -> List[str]:
    """Return the canonical role list to filter by."""
    if client_roles:
        return normalize_client_roles(client_roles)
    if analysis is not None:
        return normalize_client_roles(getattr(analysis, "client_roles", None) or [])
    return []


def _brd_to_obligation_map(
    analysis: Optional[RegulatoryAnalysis],
) -> Dict[str, Obligation]:
    """Return ``{source_requirement_id (BR-XXX) -> Obligation}``.

    The questionnaire's ``mapped_requirement_ids`` are BRD IDs, so this is
    the join key used by :func:`_apply_role_filter`.
    """
    result: Dict[str, Obligation] = {}
    if analysis is None:
        return result
    for obligation in analysis.obligations or []:
        for key in (obligation.source_requirement_id, obligation.obligation_id):
            if key and key not in result:
                result[key] = obligation
    return result


def _question_role_verdict(
    question: Mapping[str, Any],
    obligations_by_brd: Mapping[str, Obligation],
    roles: Sequence[str],
) -> Dict[str, Any]:
    """Aggregate role applicability across every obligation the question maps to.

    Returns::

        {
            "keep":               bool,
            "applicable_roles":   [role, ...],
            "partial_roles":      [role, ...],
            "uncertain_roles":    [role, ...],
            "not_applicable_roles": [role, ...],
            "verdict":            "Applicable" | "Partially Applicable" | ...,
            "rationales":         {role: text, ...},
        }

    Questions with no obligation mapping are always kept and marked
    ``Uncertain`` for every role (SME review) rather than dropped, so the
    role filter never silently loses questionnaire coverage.
    """
    mapped_ids = list(question.get("mapped_requirement_ids") or [])
    matched_obligations: List[Obligation] = [
        obligations_by_brd[m] for m in mapped_ids if m in obligations_by_brd
    ]
    role_set = list(roles)
    if not matched_obligations:
        return {
            "keep": True,
            "applicable_roles": [],
            "partial_roles": [],
            "uncertain_roles": list(role_set),
            "not_applicable_roles": [],
            "verdict": APPLICABILITY_UNCERTAIN,
            "rationales": {
                r: (
                    "Question does not map to a role-tagged obligation; "
                    "kept in scope for SME review."
                )
                for r in role_set
            },
        }

    applicable: set = set()
    partial: set = set()
    uncertain: set = set()
    not_applicable: set = set()
    rationales: Dict[str, str] = {}

    for obligation in matched_obligations:
        for record in obligation.role_applicability or []:
            role = str(record.get("role") or "")
            if role not in role_set:
                continue
            applicability = str(record.get("applicability") or "")
            rationale = str(record.get("rationale") or "")
            if applicability == APPLICABILITY_APPLICABLE:
                applicable.add(role)
            elif applicability == APPLICABILITY_PARTIAL:
                partial.add(role)
            elif applicability == APPLICABILITY_UNCERTAIN:
                uncertain.add(role)
            elif applicability == APPLICABILITY_NOT_APPLICABLE:
                not_applicable.add(role)
            if rationale and role not in rationales:
                rationales[role] = f"[{applicability}] {rationale}"

    in_scope = applicable | partial | uncertain
    keep = bool(in_scope)  # drop only if every selected role is Not Applicable

    if applicable:
        verdict = APPLICABILITY_APPLICABLE
    elif partial:
        verdict = APPLICABILITY_PARTIAL
    elif uncertain:
        verdict = APPLICABILITY_UNCERTAIN
    else:
        verdict = APPLICABILITY_NOT_APPLICABLE

    return {
        "keep": keep,
        "applicable_roles": sorted(applicable),
        "partial_roles": sorted(partial),
        "uncertain_roles": sorted(uncertain),
        "not_applicable_roles": sorted(not_applicable),
        "verdict": verdict,
        "rationales": rationales,
    }


def _apply_role_filter(
    package: Dict[str, Any],
    *,
    analysis: Optional[RegulatoryAnalysis],
    client_roles: Sequence[str],
    regulation: str,
) -> None:
    """Drop / annotate questions based on the selected client roles.

    Mutates ``package`` in place. Adds:

    * ``metadata.client_roles`` — canonical institution names.
    * ``metadata.role_interpretation`` — copy of Agent 1's
      :class:`~services.client_roles.RoleAwareInterpretation` (dict form) so
      the UI can render the interpretation bundle even when the analysis is
      not reloaded from session state.
    * Per-question ``role_applicability`` block with the verdict, rationale,
      and applicable role list.

    Every kept question also gets its ``explainability`` bundle enriched
    with ``client_roles``, ``role_verdict`` and per-role rationale strings
    so the "Why am I being asked this?" panel can quote the reasoning.
    """
    roles = list(client_roles)
    obligations_by_brd = _brd_to_obligation_map(analysis)

    original_questions: List[Dict[str, Any]] = list(package.get("questions") or [])
    kept: List[Dict[str, Any]] = []
    dropped: List[Dict[str, Any]] = []

    for question in original_questions:
        verdict = _question_role_verdict(question, obligations_by_brd, roles)
        role_block = {
            "verdict": verdict["verdict"],
            "applicable_roles": verdict["applicable_roles"],
            "partial_roles": verdict["partial_roles"],
            "uncertain_roles": verdict["uncertain_roles"],
            "not_applicable_roles": verdict["not_applicable_roles"],
            "rationales": verdict["rationales"],
            "client_roles": list(roles),
        }
        question["role_applicability"] = role_block

        explain = dict(question.get("explainability") or {})
        explain.setdefault("regulation", regulation)
        explain["client_roles"] = list(roles)
        explain["role_verdict"] = verdict["verdict"]
        explain["applicable_client_roles"] = verdict["applicable_roles"] + verdict["partial_roles"]
        explain["role_rationale"] = verdict["rationales"]
        question["explainability"] = explain

        if verdict["keep"]:
            kept.append(question)
        else:
            question["out_of_scope_reason"] = (
                f"Not applicable to any of the selected institution "
                f"type(s): {', '.join(roles)}."
            )
            dropped.append(question)

    package["questions"] = kept

    metadata = dict(package.get("metadata") or {})
    metadata["client_roles"] = list(roles)
    metadata["role_filter_applied"] = True
    metadata["questions_dropped_out_of_scope"] = len(dropped)
    metadata["questions_kept_in_scope"] = len(kept)
    if analysis is not None and getattr(analysis, "role_interpretation", None):
        metadata["role_interpretation"] = dict(analysis.role_interpretation)
    package["metadata"] = metadata

    # Preserve the dropped list on the package (audit trail; UI can surface
    # "Excluded for the selected institution type" section if desired).
    package["out_of_scope_questions"] = dropped


__all__ = ["QuestionnaireAgent"]
